"""Capability Agent — LLM-based question generation from capabilities.

The agent ONLY sees:
  - Capability name and description
  - Trust boundary (what crosses the boundary)
  - Input source (user-controlled? system?)
  - Output destination (where does the value go?)
  - Relevant invariant (what property must hold)

It does NOT see raw source code. This forces reasoning
about the SECURITY CONTRACT rather than pattern-matching APIs.

Output: A list of Questions about trust boundary violations,
invariant breaks, and state inconsistencies.

Pipeline::

    CapabilityDiscoveryEngine (deterministic)
              ↓
    CapabilityResult[features, invariants, questions]
              ↓
    CapabilityAgent.analyze() (LLM)
              ↓
    Generated Questions + Hypotheses
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field, asdict
from typing import Any, Callable

logger = logging.getLogger(__name__)


@dataclass
class CapabilityContext:
    """Structured context for the LLM — no raw code."""

    function_name: str = ""
    """Name of the function (may hint at capability)."""

    file_path: str = ""
    """File path (for traceability, not code content)."""

    capability_name: str = ""
    """Detected business capability, e.g. 'Reference Expansion'."""

    capability_description: str = ""
    """What this capability enables the user to do."""

    trust_boundary: str = ""
    """What trust boundary is involved, e.g. 'Secret → Resolved → Output'."""

    input_source: str = ""
    """Where the input comes from, e.g. 'User-controlled API request'."""

    output_destination: str = ""
    """Where the output goes, e.g. 'Sent to external API as api_key'."""

    relevant_invariant: str = ""
    """Security invariant that should hold, e.g. 'Secret must be opaque'."""

    code_summary: str = ""
    """One-line summary of what the code does (generated by discovery engine,
    not raw code)."""


@dataclass
class GeneratedQuestion:
    """A question generated by the Capability Agent."""

    id: str = ""
    """Unique question ID, auto-generated."""

    question: str = ""
    """The question about security implications."""

    probes_invariant: str = ""
    """Which invariant is being probed."""

    severity_hint: str = "medium"
    """Hint: high / medium / low (preliminary, not a verdict)."""

    reasoning: str = ""
    """Why the agent thinks this question matters."""


@dataclass
class CapabilityAnalysis:
    """Complete output of Capability Agent analysis."""

    context: CapabilityContext = field(default_factory=CapabilityContext)
    questions: list[GeneratedQuestion] = field(default_factory=list)
    hypothesis: str = ""
    """A preliminary hypothesis about what could go wrong."""

    confidence: int = 0
    """Confidence that the analysis is meaningful (1-10)."""


class CapabilityAgent:
    """LLM-powered agent that analyzes capabilities and generates questions.

    The agent does NOT read source code. It only sees the capability
    abstraction: what the code enables, what trust boundary it crosses,
    what invariant should hold.
    """

    def __init__(self, llm_call: Callable[[str], str] | None = None):
        self._llm_call = llm_call
        self._question_counter = 0

    def _next_q_id(self) -> str:
        self._question_counter += 1
        return f"Q-CAP-{self._question_counter:03d}"

    def analyze(self, context: CapabilityContext) -> CapabilityAnalysis:
        """Run the capability agent on a single capability context.

        Parameters
        ----------
        context : CapabilityContext
            Structured capability context (no raw code).

        Returns
        -------
        CapabilityAnalysis
        """
        if self._llm_call is None:
            return self._fallback_analyze(context)

        prompt = self._build_prompt(context)
        try:
            response = self._llm_call(prompt)

            # Try to parse as JSON
            if isinstance(response, str):
                # Strip markdown fences if present
                content = response.strip()
                if content.startswith("```"):
                    content = content.split("\n", 1)[-1]
                    content = content.rsplit("\n```", 1)[0]
                content = content.strip()

                parsed = json.loads(content)
            elif hasattr(response, "content"):
                parsed = json.loads(response.content)
            else:
                parsed = json.loads(response)

            questions = []
            for q_entry in parsed.get("questions", []):
                questions.append(GeneratedQuestion(
                    id=self._next_q_id(),
                    question=q_entry.get("question", ""),
                    probes_invariant=q_entry.get("probes_invariant", ""),
                    severity_hint=q_entry.get("severity_hint", "medium"),
                    reasoning=q_entry.get("reasoning", ""),
                ))

            return CapabilityAnalysis(
                context=context,
                questions=questions,
                hypothesis=parsed.get("hypothesis", ""),
                confidence=parsed.get("confidence", 5),
            )

        except (json.JSONDecodeError, KeyError, TypeError) as e:
            logger.warning("CapabilityAgent LLM parse failed: %s", e)
            return self._fallback_analyze(context)

    def _build_prompt(self, context: CapabilityContext) -> str:
        """Build a prompt that only shows capability abstraction, no code."""
        return f"""You are a security reasoning engine. You do NOT look for specific APIs.
You reason about BUSINESS CAPABILITIES and what they imply for security.

## Context (no source code)

- Function: {context.function_name}
- Capability: {context.capability_name}
- Description: {context.capability_description}
- Trust Boundary: {context.trust_boundary}
- Input Source: {context.input_source}
- Output Destination: {context.output_destination}
- Relevant Invariant: {context.relevant_invariant}
- Code Summary: {context.code_summary}

## Instructions

1. Based ONLY on the capability above, generate 2-4 security questions.
2. Each question should probe a specific trust boundary, invariant, or state change.
3. For each question, explain WHY it matters (what could go wrong).
4. Optionally provide a hypothesis: "If X is true, then Y could happen."

## Output Format (JSON only)

{{
  "questions": [
    {{
      "question": "Why is this capability needed here?",
      "probes_invariant": "secret_opaque",
      "severity_hint": "high",
      "reasoning": "This capability expands a reference into a value..."
    }}
  ],
  "hypothesis": "If the reference name is user-controlled, an attacker can...",
  "confidence": 7
}}
"""

    def _fallback_analyze(self, context: CapabilityContext) -> CapabilityAnalysis:
        """Fallback when no LLM is available — use deterministic question generation."""
        # Generate basic questions from the capability context
        questions = [
            GeneratedQuestion(
                id=self._next_q_id(),
                question=f"Does {context.capability_name} introduce a new trust boundary?",
                probes_invariant=context.relevant_invariant,
                severity_hint="high",
                reasoning=f"The capability '{context.capability_name}' involves "
                          f"a trust boundary: {context.trust_boundary}",
            ),
            GeneratedQuestion(
                id=self._next_q_id(),
                question=f"Is the input source '{context.input_source}' trusted?",
                probes_invariant=context.relevant_invariant,
                severity_hint="medium",
                reasoning=f"The input comes from {context.input_source} "
                          f"and reaches {context.output_destination}",
            ),
            GeneratedQuestion(
                id=self._next_q_id(),
                question=f"Does the invariant '{context.relevant_invariant}' still hold?",
                probes_invariant=context.relevant_invariant,
                severity_hint="high",
                reasoning=f"The capability {context.capability_name} may violate "
                          f"the invariant '{context.relevant_invariant}'",
            ),
        ]

        return CapabilityAnalysis(
            context=context,
            questions=questions,
            hypothesis=f"{context.capability_name} may enable access to "
                       f"sensitive data via {context.output_destination}",
            confidence=5,
        )

    def analyze_batch(self, contexts: list[CapabilityContext]) -> list[CapabilityAnalysis]:
        """Analyze multiple capability contexts in batch.

        Parameters
        ----------
        contexts : list[CapabilityContext]
            Multiple capability contexts.

        Returns
        -------
        list[CapabilityAnalysis]
        """
        return [self.analyze(ctx) for ctx in contexts]


# ---------------------------------------------------------------------------
# Convenience: build CapabilityContext from CapabilityResult
# ---------------------------------------------------------------------------

def build_context(result) -> CapabilityContext:
    """Build a CapabilityContext from a CapabilityResult (discovery output).

    Parameters
    ----------
    result : CapabilityResult
        Output of CapabilityDiscoveryEngine.

    Returns
    -------
    CapabilityContext
    """
    feature_names = ", ".join(f.name for f in result.features)
    inv_names = ", ".join(inv.name for inv in result.invariants[:3])

    # Build trust boundary description from features
    boundary_parts = []
    for feat in result.features:
        if "secret" in feat.id or "reference" in feat.id:
            boundary_parts.append("Secret → Resolved → Output")
        elif "plugin" in feat.id or "remote" in feat.id:
            boundary_parts.append("External Source → Internal Execution")
        elif "auth" in feat.id:
            boundary_parts.append("User Identity → System Access")
        elif "config" in feat.id:
            boundary_parts.append("Config Source → Runtime State")
        elif "network" in feat.id or "proxy" in feat.id or "request" in feat.id:
            boundary_parts.append("Internal → External Network")
        else:
            boundary_parts.append(f"{feat.name} → System")

    return CapabilityContext(
        function_name=result.function_name,
        file_path=result.file_path,
        capability_name=feature_names or "Unknown",
        capability_description=(
            result.features[0].description if result.features
            else "No capability description available"
        ),
        trust_boundary=" | ".join(boundary_parts) if boundary_parts else "Unknown",
        input_source="User-controlled (via API/frontend)" if "user" in str(result.source_code).lower() else "System-controlled",
        output_destination="External API / network" if any(
            "remote" in f.id or "network" in f.id or "proxy" in f.id
            for f in result.features
        ) else "Internal processing",
        relevant_invariant=inv_names or "None",
        code_summary=f"Function {result.function_name} in {result.file_path}",
    )
