"""CI/CD workflow templates for agies."""

GITHUB_ACTIONS = """# agies security audit workflow
# Generated by `agies init --ci`
#
# This workflow runs a quick scan on every push/PR.
# For a full LLM-powered audit, set AGIES_MODEL and AGIES_API_KEY in secrets.

name: agies security audit

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  issues: write
  checks: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install agies
        run: |
          pip install agies

      - name: Initialize config (if not present)
        run: |
          agies init . || true

      - name: Run quick scan
        run: |
          agies scan . -o agies-report.json

      - name: Upload scan results
        uses: actions/upload-artifact@v4
        with:
          name: agies-scan-report
          path: agies-report.json

      - name: Run full audit (if API key configured)
        if: ${{ secrets.AGIES_API_KEY != '' }}
        env:
          AGIES_API_KEY: ${{ secrets.AGIES_API_KEY }}
        run: |
          agies audit . --output agies-audit-report.md

      - name: Upload audit report
        if: ${{ secrets.AGIES_API_KEY != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: agies-audit-report
          path: agies-audit-report.md
"""

GITLAB_CI = """# agies security audit — GitLab CI
# Generated by `agies init --ci`

stages:
  - security

agies-scan:
  stage: security
  image: python:3.11
  script:
    - pip install agies
    - agies init . || true
    - agies scan . -o agies-report.json
  artifacts:
    paths:
      - agies-report.json
    when: always
  only:
    - main
    - master
    - develop

agies-audit:
  stage: security
  image: python:3.11
  script:
    - pip install agies
    - agies audit . --output agies-audit-report.md
  artifacts:
    paths:
      - agies-audit-report.md
    when: always
  only:
    - main
  variables:
    DEEPSEEK_API_KEY: $DEEPSEEK_API_KEY  # Set in CI/CD settings
"""

PRE_COMMIT = r"""#!/bin/bash
# agies pre-commit hook — run scan on staged files
# Generated by `agies init --ci`
# Install: cp .agies/ci/pre-commit.sh .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit

set -e

echo "🔍 agies: scanning staged files..."

# Get staged Python files
STAGED=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$' || true)

if [ -z "$STAGED" ]; then
    echo "  No Python files staged, skipping."
    exit 0
fi

# Run agies scan on the whole project (includes static analysis)
if command -v agies &> /dev/null; then
    agies scan . -o /tmp/agies-precommit.json 2>/dev/null || true

    # Check for critical/high findings
    if [ -f /tmp/agies-precommit.json ]; then
        CRITICAL=$(python3 -c "
import json
with open('/tmp/agies-precommit.json') as f:
    data = json.load(f)
critical = [f for f in data.get('static_findings', []) if f.get('severity') in ('critical', 'high')]
for f in critical:
    print(f[\"severity\"].upper() + ': ' + f[\"title\"] + ' (' + f.get(\"file\", \"\") + ')')
" 2>/dev/null)

        if [ -n "$CRITICAL" ]; then
            echo "❌ agies: critical/high findings detected:"
            echo "$CRITICAL"
            echo ""
            echo "To commit anyway: git commit --no-verify"
            exit 1
        fi
    fi
fi

echo "✅ agies: scan passed"
exit 0
"""


def get_template(name: str) -> str:
    """Get a CI template by name."""
    templates = {
        "github-actions": GITHUB_ACTIONS,
        "gitlab-ci": GITLAB_CI,
        "pre-commit": PRE_COMMIT,
    }
    return templates.get(name, "")
