"""Project configuration for agies audits.

Config is loaded from `.agies/config.yml` in the project root.
"""

import os
from dataclasses import dataclass, field
from typing import Optional

DEFAULT_CONFIG_DIR = ".agies"
DEFAULT_CONFIG_FILE = "config.yml"


@dataclass
class LLMConfig:
    model: str = "deepseek-chat"
    strong_model: Optional[str] = None


@dataclass
class StrategyConfig:
    phase1_ratio: float = 0.2
    phase1_min_files: int = 10
    phase1_max_files: int = 100
    chunk_target_tokens: int = 30000


@dataclass
class VerificationConfig:
    enabled: bool = True
    cross_model_enabled: bool = True


@dataclass
class ReportConfig:
    format: str = "markdown"
    output: str = ""


@dataclass
class ProjectConfig:
    name: str = ""
    languages: list[str] = field(default_factory=list)
    exclude_patterns: list[str] = field(default_factory=lambda: [
        "node_modules/*", ".git/*", "__pycache__/*",
        ".venv/*", "venv/*", "dist/*", "build/*",
    ])

    llm: LLMConfig = field(default_factory=LLMConfig)
    strategy: StrategyConfig = field(default_factory=StrategyConfig)
    verification: VerificationConfig = field(default_factory=VerificationConfig)
    report: ReportConfig = field(default_factory=ReportConfig)


# Default config template for `agies init`
DEFAULT_CONFIG_YAML = """# agies project configuration
# Generated by `agies init`

project:
  name: "{name}"
  languages: [{languages}]
  exclude_patterns:
    - node_modules/*
    - .git/*
    - __pycache__/*
    - .venv/*
    - venv/*
    - dist/*
    - build/*

llm:
  model: deepseek-chat
  # strong_model: claude-opus-4-7  # uncomment for cross-model verification

strategy:
  phase1_ratio: 0.2
  phase1_min_files: 10
  phase1_max_files: 100
  chunk_target_tokens: 30000

verification:
  enabled: true
  cross_model_enabled: false  # requires strong_model to be set

report:
  format: markdown
  # output: audit-report.md  # uncomment to auto-save
"""


def find_project_root(target: str = ".") -> str:
    """Walk up from target to find project root (has .git dir or pyproject.toml)."""
    target = os.path.abspath(target)
    if os.path.isfile(target):
        target = os.path.dirname(target)

    current = target
    while True:
        if os.path.exists(os.path.join(current, ".git")):
            return current
        if os.path.exists(os.path.join(current, "pyproject.toml")):
            return current
        parent = os.path.dirname(current)
        if parent == current:
            return target  # Hit filesystem root, use original
        current = parent


def detect_languages(target: str = ".") -> list[str]:
    """Detect programming languages in the target directory."""
    from agies.core import collect_context
    ctx = collect_context(target)
    return ctx.get("languages", [])


def init_config(target: str = ".", ci: bool = False) -> str:
    """Initialize .agies/config.yml in the project root.

    Returns the path to the created config file.
    """
    project_root = find_project_root(target)
    config_dir = os.path.join(project_root, DEFAULT_CONFIG_DIR)
    config_path = os.path.join(config_dir, DEFAULT_CONFIG_FILE)

    os.makedirs(config_dir, exist_ok=True)

    # Auto-detect
    languages = detect_languages(project_root)
    project_name = os.path.basename(project_root)

    # Generate config
    lang_str = ", ".join(f'"{l}"' for l in languages)
    config_content = DEFAULT_CONFIG_YAML.format(
        name=project_name,
        languages=lang_str,
    )

    with open(config_path, "w") as f:
        f.write(config_content)

    # Create .gitignore entry if needed
    gitignore_path = os.path.join(project_root, ".gitignore")
    agies_entry = ".agies/reports/"

    if os.path.exists(gitignore_path):
        with open(gitignore_path) as f:
            if agies_entry not in f.read():
                with open(gitignore_path, "a") as f2:
                    f2.write(f"\n# agies audit reports\n{agies_entry}\n")

    # Generate CI/CD templates if requested
    if ci:
        _generate_ci_templates(project_root, config_dir)

    return config_path


def _generate_ci_templates(project_root: str, config_dir: str):
    """Generate CI/CD workflow templates."""
    from .ci_templates import get_template

    ci_dir = os.path.join(config_dir, "ci")
    os.makedirs(ci_dir, exist_ok=True)

    templates = [
        ("github-actions.yml", get_template("github-actions")),
        ("gitlab-ci.yml", get_template("gitlab-ci")),
        ("pre-commit.sh", get_template("pre-commit")),
    ]

    for filename, content in templates:
        if content:
            path = os.path.join(ci_dir, filename)
            with open(path, "w") as f:
                f.write(content)
            # Make shell scripts executable
            if filename.endswith(".sh"):
                os.chmod(path, 0o755)
            print(f"  Created: {path}")

    # Optionally install pre-commit hook
    hook_path = os.path.join(project_root, ".git", "hooks", "pre-commit")
    if os.path.isdir(os.path.dirname(hook_path)):
        import shutil
        shutil.copy2(os.path.join(ci_dir, "pre-commit.sh"), hook_path)


def load_config(target: str = ".") -> ProjectConfig:
    """Load project config from .agies/config.yml.

    Returns default config if no config file exists.
    """
    config_path = os.path.join(find_project_root(target), DEFAULT_CONFIG_DIR, DEFAULT_CONFIG_FILE)
    if not os.path.exists(config_path):
        return ProjectConfig()

    try:
        import yaml
        with open(config_path) as f:
            data = yaml.safe_load(f) or {}
    except ImportError:
        return ProjectConfig()

    cfg = ProjectConfig()

    # Project section
    proj = data.get("project", {})
    cfg.name = proj.get("name", cfg.name)
    cfg.languages = proj.get("languages", cfg.languages)
    cfg.exclude_patterns = proj.get("exclude_patterns", cfg.exclude_patterns)

    # LLM section
    llm = data.get("llm", {})
    cfg.llm.model = llm.get("model", cfg.llm.model)
    cfg.llm.strong_model = llm.get("strong_model", cfg.llm.strong_model)

    # Strategy section
    strat = data.get("strategy", {})
    cfg.strategy.phase1_ratio = strat.get("phase1_ratio", cfg.strategy.phase1_ratio)
    cfg.strategy.phase1_min_files = strat.get("phase1_min_files", cfg.strategy.phase1_min_files)
    cfg.strategy.phase1_max_files = strat.get("phase1_max_files", cfg.strategy.phase1_max_files)
    cfg.strategy.chunk_target_tokens = strat.get("chunk_target_tokens", cfg.strategy.chunk_target_tokens)

    # Verification section
    ver = data.get("verification", {})
    cfg.verification.enabled = ver.get("enabled", cfg.verification.enabled)
    cfg.verification.cross_model_enabled = ver.get("cross_model_enabled", cfg.verification.cross_model_enabled)

    # Report section
    rpt = data.get("report", {})
    cfg.report.format = rpt.get("format", cfg.report.format)
    cfg.report.output = rpt.get("output", cfg.report.output)

    return cfg
