"""Synthesis Agent — cross-blackboard blind spot detection & hypothesis generation.

Phase E-1: After all phase results are collected, the Synthesis Agent reads the
blackboard to find:

1. **Blind spots**: Functions with capability questions but NO path analysis.
   The sink-based pipeline never considered them, but capability analysis
   flagged them. The agent reads the actual source code to determine if
   the blind spot is genuinely exploitable.

2. **Cross-cutting patterns**: A capability question from function A that is
   relevant to a finding in function B (connecting unrelated paths).

3. **Attack chain hypotheses**: Combining capability questions + phase results
   + source code into new attack narratives.

Each hypothesis can be:
  - Promoted to a new AgentPhaseResult (fed back into report)
  - Sent directly to PoC Agent for exploit generation
  - Recorded as blackboard knowledge for the final synthesis report

Design
------
The agent gets full source code access and LLM privileges. It is intentionally
over-zealous: it should flag anything that looks connected, even weakly.
Downstream (PoC Agent, report) filters out noise.

Usage::

    from agies.engine.v3.agents.synthesis_agent import SynthesisAgent

    agent = SynthesisAgent(blackboard, function_index, llm_call)
    new_findings, poc_requests = agent.synthesize(
        phase_results=phase_results,
        chain_results=chain_results,
        path_slices=path_slices,
        project_path=target,
    )
    # Merge new_findings into all_results for report
    # Feed poc_requests to PoCAgent
"""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass, field
from typing import Any, Callable

from agies.engine.v3.aggregator.models import AgentPhaseResult

logger = logging.getLogger(__name__)


@dataclass
class SynthesisHypothesis:
    """A hypothesis generated by the Synthesis Agent."""

    title: str
    """Short label, e.g. 'Secret Expansion → SSRF Bypass'."""

    description: str
    """What the hypothesis claims — readable summary."""

    confidence: int
    """0-10: how confident the agent is in this hypothesis."""

    source_functions: list[str] = field(default_factory=list)
    """Functions involved in the hypothesis."""

    related_capabilities: list[str] = field(default_factory=list)
    """Capability names that triggered this hypothesis."""

    related_path_ids: list[str] = field(default_factory=list)
    """Path IDs connected by this hypothesis."""

    evidence: str = ""
    """Supporting evidence — code snippets, data flow notes."""

    requires_poc: bool = False
    """If True, this hypothesis is concrete enough for PoC generation."""

    poc_reasoning: str = ""
    """Why a PoC is warranted (for the PoC Agent prompt)."""


@dataclass
class SynthesisResult:
    """Complete output of the Synthesis Agent."""

    hypotheses: list[SynthesisHypothesis] = field(default_factory=list)
    """Generated hypotheses about blind spots and attack chains."""

    new_findings: list[AgentPhaseResult] = field(default_factory=list)
    """New findings promoted to report-level (high confidence only)."""

    synthesis_report: str = ""
    """Free-text summary of all cross-cutting connections found."""


# Deterministic patterns for capability → attack chain mapping.
# When a function has a capability AND a vulnerability type co-occur,
# the system checks these patterns for cross-cutting relevance.
_CAPABILITY_VULN_LINKS: dict[str, list[str]] = {
    "reference_expansion": [
        "ssrf", "lfi", "ssti", "sqli",
    ],
    "secret_management": [
        "ssrf", "rce", "sqli",
    ],
    "remote_acquisition": [
        "ssrf", "rce", "lfi",
    ],
    "configuration_loading": [
        "rce", "lfi", "ssrf", "sqli",
    ],
    "plugin_loading": [
        "rce", "ssti", "lfi",
    ],
    "object_reference": [
        "idor", "afo", "lfi",
    ],
    "data_serialization": [
        "rce", "sqli",
    ],
    "credential_handling": [
        "ssrf", "rce",
    ],
    "dynamic_import": [
        "rce", "lfi",
    ],
}

# Source code patterns that indicate real exploit potential.
# Each pattern contributes to the blind spot confidence boost.
_SOURCE_DANGER_PATTERNS: list[tuple[str, int, str]] = [
    # (regex, confidence_boost, description)
    (r"os\.environ(?:\.get|\[)", 3, "reads environment variable"),
    (r"os\.getenv\(", 3, "reads environment variable"),
    (r"\beval\s*\(", 4, "calls eval() — arbitrary code execution"),
    (r"\bexec\s*\(", 4, "calls exec() — arbitrary code execution"),
    (r"subprocess\.(?:call|Popen|run|check_output)", 4, "shell command execution"),
    (r"os\.system\s*\(", 4, "shell command execution"),
    (r"pickle\.(?:loads?|Unpickler)\s*\(", 4, "unsafe deserialization via pickle"),
    (r"yaml\.load\s*\(", 3, "unsafe YAML deserialization (not safe_load)"),
    (r"requests\.(?:get|post|put|delete|patch|request)\s*\(", 3, "outbound HTTP request"),
    (r"urllib3?\.request", 3, "outbound HTTP request"),
    (r"\bopen\s*\([^)]*[wab]", 2, "file write operation"),
    (r"flask\.request|request\.(?:args|form|json|data|cookies|headers)", 3, "reads HTTP request input"),
    (r"request\.get_json\s*\(|request\.get_data\s*\(", 3, "reads HTTP request body"),
    (r"\binput\s*\(\s*['\"]", 2, "reads user input"),
    (r"sqlite3\.(?:connect|execute)|cursor\.execute", 3, "database access"),
    (r"\$\{?\w+\}?", 2, "string interpolation / variable expansion"),
    (r"__import__\s*\(|importlib\.import_module", 3, "dynamic import"),
    (r"tempfile\.(?:mkstemp|mkdtemp|NamedTemporaryFile)", 2, "temporary file creation"),
    (r"\bexec\w*\s*\(|compile\s*\(", 4, "dynamic code compilation/execution"),
]


class SynthesisAgent:
    """Cross-blackboard blind spot detection & hypothesis generation.

    Reads capability questions from Phase B-1, cross-references with
    Phase D results, reads source code for blind spots, and generates
    attack chain hypotheses.
    """

    def __init__(
        self,
        blackboard: Any,
        function_index: Any | None = None,
        llm_call: Callable[[str], str] | None = None,
    ) -> None:
        self._blackboard = blackboard
        self._function_index = function_index
        self._llm_call = llm_call

    # ------------------------------------------------------------------
    # Phase 1: Collect capability questions & analyzed functions
    # ------------------------------------------------------------------

    def _collect_capability_questions(self) -> dict[str, list[str]]:
        """Collect all capability questions from the blackboard.

        Returns: function_name → list of capability questions.
        """
        fn_questions: dict[str, list[str]] = {}
        try:
            knowledge = self._blackboard._knowledge
            for key, entries in knowledge.items():
                for entry in entries:
                    if entry.source_path_id == "phase-b-1" and entry.value.startswith("[capability]"):
                        if key not in fn_questions:
                            fn_questions[key] = []
                        fn_questions[key].append(entry.value)
        except Exception:
            logger.debug("SynthesisAgent: could not read blackboard knowledge", exc_info=True)
        return fn_questions

    # ------------------------------------------------------------------
    # Phase 2: Source code lookup
    # ------------------------------------------------------------------

    @staticmethod
    def _collect_analyzed_path_ids(phase_results: list[AgentPhaseResult]) -> set[str]:
        """Collect all path IDs that were analyzed in Phase D."""
        return {r.path_id for r in phase_results}


    def _lookup_source(self, fn_name: str) -> tuple[str, str, str]:
        """Look up a function's source code from function_index.

        Returns: (source_body, file_path, signature)
        """
        if not self._function_index:
            return ("", "", "")

        try:
            matches = self._function_index.lookup(fn_name)
            if matches:
                fn = matches[0]
                body = fn.body or ""
                fpath = fn.file_path or ""
                sig = fn.signature or ""
                return (body, fpath, sig)
        except Exception:
            logger.debug("SynthesisAgent: lookup failed for %s", fn_name)
        return ("", "", "")

    def _analyze_source(self, source: str) -> list[dict[str, Any]]:
        """Deterministic analysis of source code for danger signals.

        Returns list of findings: [(pattern, confidence_delta, description)]
        """
        findings: list[dict[str, Any]] = []
        for pattern, boost, desc in _SOURCE_DANGER_PATTERNS:
            matches = re.findall(pattern, source)
            if matches:
                findings.append({
                    "pattern": pattern,
                    "boost": boost,
                    "description": desc,
                    "match_count": len(matches),
                })
        return findings

    # ------------------------------------------------------------------
    # Phase 2: Blind spot detection WITH source code analysis
    # ------------------------------------------------------------------

    def _find_blind_spots(
        self,
        fn_questions: dict[str, list[str]],
        analyzed_paths: set[str],
        path_slices: list[Any] | None,
    ) -> list[SynthesisHypothesis]:
        """Find functions with capability questions but NO path analysis.

        For each blind spot, reads the actual source code and analyzes it
        for danger signals. Boosts confidence based on findings.
        """
        # Collect all function names that appear in path slices
        analyzed_fns: set[str] = set()
        if path_slices:
            for sl in path_slices:
                if hasattr(sl, "nodes"):
                    for node in sl.nodes:
                        fn = (
                            getattr(node, "function_name", None)
                            or (node if isinstance(node, str) else None)
                        )
                        if fn:
                            analyzed_fns.add(fn)

        hypotheses: list[SynthesisHypothesis] = []
        for fn_name, questions in fn_questions.items():
            if fn_name in analyzed_fns:
                continue

            # Read source code for this function
            source, file_path, signature = self._lookup_source(fn_name)
            source_analysis = self._analyze_source(source) if source else []

            # Base confidence: 4 for having capability questions
            confidence = 4 + min(len(questions), 2)
            source_evidence_parts: list[str] = []
            total_boost = 0

            for finding in source_analysis:
                boost = finding["boost"]
                total_boost += boost
                source_evidence_parts.append(
                    f"  [{'+' * boost}] {finding['description']} "
                    f"({finding['match_count']} match(es))"
                )

            # Cap confidence boost to avoid over-scoring on regex hits
            confidence = min(confidence + total_boost, 9)

            # Determine if PoC-worthy: high confidence AND real exploit signals
            has_env_var = any("environment variable" in f["description"] for f in source_analysis)
            has_network = any("HTTP request" in f["description"] for f in source_analysis)
            has_exec = any(
                kw in f["description"] for f in source_analysis
                for kw in ["code execution", "shell command", "eval", "unsafe deserialize"]
            )
            has_user_input = any("HTTP request input" in f["description"] for f in source_analysis)
            requires_poc = (
                confidence >= 7
                and (
                    has_env_var or has_network or has_exec or has_user_input
                )
            )

            # Build evidence string
            evidence = "\n".join(questions[:3])
            if file_path:
                evidence += f"\n\nSource: {file_path}"
                if signature:
                    evidence += f"\nSignature: {signature}"
            if source_evidence_parts:
                snippet = self._extract_snippet(source)
                if snippet:
                    evidence += f"\n\n```python\n{snippet}\n```"
                evidence += "\n\nSource analysis:\n" + "\n".join(source_evidence_parts)

            hypotheses.append(SynthesisHypothesis(
                title=f"Blind spot: {fn_name}",
                description=(
                    f"Function '{fn_name}' has {len(questions)} capability question(s)"
                    + (f" in {file_path}" if file_path else "")
                    + (f" but was never analyzed by any path agent."
                       if not source_analysis
                       else f". Source analysis found {len(source_analysis)} danger signal(s) "
                           f"(total boost: +{total_boost}, final conf: {confidence}).")
                ),
                confidence=confidence,
                source_functions=[fn_name],
                related_capabilities=[
                    q.split("(invariant:")[0].replace("[capability]", "").strip()
                    for q in questions[:3]
                ],
                evidence=evidence,
                requires_poc=requires_poc,
                poc_reasoning=(
                    f"Blind spot '{fn_name}' has capability questions and source analysis "
                    f"found {len(source_analysis)} danger signal(s) "
                    f"({' '.join(f['description'] for f in source_analysis[:3])}). "
                    f"The sink-based pipeline completely missed this function."
                ) if requires_poc else "",
            ))
        return hypotheses

    @staticmethod
    def _extract_snippet(source: str, max_lines: int = 15) -> str:
        """Extract a readable snippet from source code."""
        lines = source.split("\n")
        if len(lines) <= max_lines:
            return source
        # Show first ~10 lines (signature + a few body lines) and last few
        return "\n".join(lines[:8] + ["  ..."] + lines[-5:])

    # ------------------------------------------------------------------
    # Phase 3: Cross-cut detection
    # ------------------------------------------------------------------

    def _find_cross_cuts(
        self,
        fn_questions: dict[str, list[str]],
        phase_results: list[AgentPhaseResult],
        path_slices: list[Any] | None,
    ) -> list[SynthesisHypothesis]:
        """Find capability questions that overlap with actual path findings.

        When a function has a capability question about e.g. 'reference expansion'
        AND is also a node in an SSRF path, that's a strong signal.
        """
        if not path_slices:
            return []

        # Build fn → path_ids mapping from path slices
        fn_to_paths: dict[str, list[str]] = {}
        for sl in path_slices:
            if hasattr(sl, "nodes"):
                for node in sl.nodes:
                    fn = getattr(node, "function_name", None) or (node if isinstance(node, str) else None)
                    if fn:
                        fn_to_paths.setdefault(fn, []).append(sl.id if hasattr(sl, "id") else str(sl))

        # Build fn → vuln_types from phase results
        fn_to_vulns: dict[str, set[str]] = {}
        for r in phase_results:
            for fn_name, paths in fn_to_paths.items():
                if r.path_id in paths:
                    fn_to_vulns.setdefault(fn_name, set()).add(r.vuln_type.lower())

        hypotheses: list[SynthesisHypothesis] = []
        for fn_name, questions in fn_questions.items():
            vuln_types = fn_to_vulns.get(fn_name, set())
            if not vuln_types:
                continue

            path_ids = fn_to_paths.get(fn_name, [])
            for q_text in questions:
                q_lower = q_text.lower()
                for cap_id, linked_vulns in _CAPABILITY_VULN_LINKS.items():
                    cap_words = cap_id.replace("_", " ").split()
                    word_match = any(w in q_lower and len(w) >= 3 for w in cap_words)
                    if not word_match:
                        continue
                    matching = [v for v in linked_vulns if v in vuln_types]
                    if matching:
                        # Also look up source for richer evidence
                        source, file_path, _ = self._lookup_source(fn_name)
                        evidence = q_text
                        if file_path:
                            evidence += f"\nSource: {file_path}"
                        if source:
                            snippet = self._extract_snippet(source)
                            evidence += f"\n\n```python\n{snippet}\n```"

                        hypotheses.append(SynthesisHypothesis(
                            title=f"Cross-cut: {cap_id} ∩ {','.join(matching)} in {fn_name}",
                            description=(
                                f"Function '{fn_name}' has capability '{cap_id}' "
                                f"and is also a node in {', '.join(matching)} path(s). "
                            ),
                            confidence=7,
                            source_functions=[fn_name],
                            related_capabilities=[cap_id],
                            related_path_ids=path_ids,
                            evidence=evidence,
                            requires_poc=True,
                            poc_reasoning=(
                                f"The capability '{cap_id}' in function '{fn_name}' "
                                f"co-occurs with {', '.join(matching)} paths. "
                            ),
                        ))
        return hypotheses

    # ------------------------------------------------------------------
    # Phase 4: LLM-based synthesis (optional)
    # ------------------------------------------------------------------

    def _llm_synthesis(
        self,
        blind_spots: list[SynthesisHypothesis],
        cross_cuts: list[SynthesisHypothesis],
        phase_results: list[AgentPhaseResult],
    ) -> SynthesisResult:
        """Optional LLM pass to generate deeper hypotheses.

        Only runs when an LLM callable is available. Uses the structured
        hypotheses from Phase 2+3 as context, including source snippets.
        """
        if not self._llm_call:
            return SynthesisResult()

        # Build context — include source evidence for top candidates
        top_spots = sorted(blind_spots + cross_cuts, key=lambda h: h.confidence, reverse=True)[:10]
        spot_summary = "\n\n".join(
            f"### {h.title} (conf={h.confidence})\n"
            f"Evidence:\n{h.evidence[:400]}"
            for h in top_spots
        ) if top_spots else "(none)"

        prompt = f"""You are a security synthesis engine with full source code access.
Your job is to read source code and identify exploitable blind spots.

## Top Candidates (with source code evidence)
{spot_summary}

## Task
Review the source code evidence above. For each candidate, determine:
1. Is there a real attack path? (user input → dangerous operation)
2. Can you identify the entry point and the sink?
3. What would a PoC look like?

Output the top 1-2 most promising attack chains in JSON format:

{{
  "hypotheses": [
    {{
      "title": "Attack chain title",
      "description": "Step-by-step with function names",
      "confidence": 8,
      "requires_poc": true,
      "poc_reasoning": "Why this is exploitable"
    }}
  ]
}}
"""
        try:
            response = self._llm_call(prompt)
            import json
            content = response.strip()
            if content.startswith("```"):
                content = content.split("\n", 1)[-1]
                content = content.rsplit("\n```", 1)[0]
            parsed = json.loads(content)
            llm_hypotheses = []
            for h in parsed.get("hypotheses", []):
                llm_hypotheses.append(SynthesisHypothesis(
                    title=h.get("title", "LLM hypothesis"),
                    description=h.get("description", ""),
                    confidence=h.get("confidence", 5),
                    requires_poc=h.get("requires_poc", False),
                    poc_reasoning=h.get("poc_reasoning", ""),
                ))
            return SynthesisResult(hypotheses=llm_hypotheses)
        except Exception as exc:
            logger.debug("SynthesisAgent LLM pass failed: %s", exc)
            return SynthesisResult()

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------

    def synthesize(
        self,
        phase_results: list[AgentPhaseResult],
        chain_results: list[AgentPhaseResult] | None = None,
        path_slices: list[Any] | None = None,
        project_path: str = "",
    ) -> SynthesisResult:
        """Run full synthesis: blind spots → cross-cuts → LLM → report.

        Parameters
        ----------
        phase_results : list[AgentPhaseResult]
            Results from Phase D Intent+Logic agents.
        chain_results : list[AgentPhaseResult], optional
            Cross-type chain correlations from Phase E.
        path_slices : list[PathSlice], optional
            Original path slices (for node-level function names).
        project_path : str
            Project root path (for source code access).

        Returns
        -------
        SynthesisResult
            Hypotheses + new findings + synthesis report.
        """
        all_results = list(phase_results)
        if chain_results:
            all_results.extend(chain_results)

        # Phase 1: Collect data
        fn_questions = self._collect_capability_questions()
        analyzed_paths = self._collect_analyzed_path_ids(all_results)

        if not fn_questions:
            logger.info("SynthesisAgent: no capability questions in blackboard, skipping")
            return SynthesisResult(
                synthesis_report="No capability questions found. Phase B-1 may have been skipped."
            )

        # Phase 2: Blind spot detection with source code analysis
        blind_spots = self._find_blind_spots(fn_questions, analyzed_paths, path_slices)

        # Phase 3: Cross-cut detection with source enrichment
        cross_cuts = self._find_cross_cuts(fn_questions, all_results, path_slices)

        # Phase 4: LLM synthesis (optional, includes source)
        llm_result = self._llm_synthesis(blind_spots, cross_cuts, all_results)

        # Compose final result
        all_hypotheses = blind_spots + cross_cuts + llm_result.hypotheses
        poc_requests = [h for h in all_hypotheses if h.requires_poc and h.confidence >= 6]

        # Build new findings for high-confidence blind spots
        new_findings: list[AgentPhaseResult] = []
        for h in blind_spots:
            if h.confidence >= 7:
                new_findings.append(AgentPhaseResult(
                    path_id=f"synthesis-blind-{len(new_findings)+1:03d}",
                    vuln_type="synthesis",
                    score=float(h.confidence),
                    confidence=h.confidence,
                    analysis=(
                        f"[SYNTHESIS AGENT — Blind Spot]\n"
                        f"Title: {h.title}\n"
                        f"Description: {h.description}\n"
                        f"Evidence:\n{h.evidence[:1000]}"
                    ),
                    is_vulnerable=True,
                ))

        # Build synthesis report
        report_parts = ["=== Synthesis Agent Report ==="]
        if blind_spots:
            report_parts.append(f"\nBlind Spots ({len(blind_spots)}):")
            for h in blind_spots:
                report_parts.append(f"  - {h.title} (conf={h.confidence})")
        if cross_cuts:
            report_parts.append(f"\nCross-Cuts ({len(cross_cuts)}):")
            for h in cross_cuts:
                report_parts.append(f"  - {h.title} (conf={h.confidence})")
        if poc_requests:
            report_parts.append(f"\nPoC Recommended ({len(poc_requests)}):")
            for h in poc_requests:
                report_parts.append(f"  - {h.title}: {h.poc_reasoning[:100]}")
        report_parts.append(f"\nNew findings promoted: {len(new_findings)}")
        synthesis_report = "\n".join(report_parts)

        return SynthesisResult(
            hypotheses=all_hypotheses,
            new_findings=new_findings,
            synthesis_report=synthesis_report,
        )
